//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B7.Processing;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
///   This class was generated by MSBuild using the GenerateResource task.
///   To add or remove a member, edit your .resx file then rerun MSBuild.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ProcessingStrings
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    public ProcessingStrings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B7.Processing.ProcessingStrings", typeof(ProcessingStrings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cannot create a failure object without a reason or at least one exception..
    /// </summary>
    public static string ERROR_CannotCreateFailureWithoutReasonOrException
    {
        get
        {
            return ResourceManager.GetString("ERROR_CannotCreateFailureWithoutReasonOrException", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Step is null..
    /// </summary>
    public static string ERROR_NullStep
    {
        get
        {
            return ResourceManager.GetString("ERROR_NullStep", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Step not found: {0}.
    /// </summary>
    public static string ERROR_StepNotFound
    {
        get
        {
            return ResourceManager.GetString("ERROR_StepNotFound", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Multiple steps with the same UUID: [{0}].
    /// </summary>
    public static string ERROR_StepsNotUnique
    {
        get
        {
            return ResourceManager.GetString("ERROR_StepsNotUnique", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0}: Validate and Cleanup.
    /// </summary>
    public static string fmt_ValidateAndCleanup
    {
        get
        {
            return ResourceManager.GetString("fmt_ValidateAndCleanup", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Executing Step: {0}.
    /// </summary>
    public static string msg_ExecutingStep
    {
        get
        {
            return ResourceManager.GetString("msg_ExecutingStep", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Finished.
    /// </summary>
    public static string msg_Finished
    {
        get
        {
            return ResourceManager.GetString("msg_Finished", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Process failed for multiple reasons..
    /// </summary>
    public static string msg_ProcessFailedForMultipleReasons
    {
        get
        {
            return ResourceManager.GetString("msg_ProcessFailedForMultipleReasons", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Step failed: {0}.
    /// </summary>
    public static string msg_StepFailed
    {
        get
        {
            return ResourceManager.GetString("msg_StepFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Step {0} of {1}.
    /// </summary>
    public static string msg_StepIndex
    {
        get
        {
            return ResourceManager.GetString("msg_StepIndex", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Validating Steps.
    /// </summary>
    public static string msg_ValidatingSteps
    {
        get
        {
            return ResourceManager.GetString("msg_ValidatingSteps", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Step is not necessary..
    /// </summary>
    public static string REASON_StepNotNecessary
    {
        get
        {
            return ResourceManager.GetString("REASON_StepNotNecessary", resourceCulture);
        }
    }
}
