//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DewIt.Model.Processing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcessingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DewIt.Model.Processing.ProcessingStrings", typeof(ProcessingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a failure object without a reason or at least one exception..
        /// </summary>
        public static string ERROR_CannotCreateFailureWithoutReasonOrException {
            get {
                return ResourceManager.GetString("ERROR_CannotCreateFailureWithoutReasonOrException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step is null..
        /// </summary>
        public static string ERROR_NullStep {
            get {
                return ResourceManager.GetString("ERROR_NullStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step not found: {0}.
        /// </summary>
        public static string ERROR_Step_not_found {
            get {
                return ResourceManager.GetString("ERROR_Step_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple steps with same UUID: [{0}].
        /// </summary>
        public static string ERROR_Steps_not_unique {
            get {
                return ResourceManager.GetString("ERROR_Steps_not_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Step: {0}.
        /// </summary>
        public static string ExecutingStep {
            get {
                return ResourceManager.GetString("ExecutingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Validate and Cleanup.
        /// </summary>
        public static string fmt_ValidateAndCleanup {
            get {
                return ResourceManager.GetString("fmt_ValidateAndCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step failed: {0}.
        /// </summary>
        public static string msg_Step_Failed {
            get {
                return ResourceManager.GetString("msg_Step_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string msg_StepIndex {
            get {
                return ResourceManager.GetString("msg_StepIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating steps.
        /// </summary>
        public static string msg_Validating_Steps {
            get {
                return ResourceManager.GetString("msg_Validating Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step is not necessary..
        /// </summary>
        public static string REASON_Step_not_Necessary {
            get {
                return ResourceManager.GetString("REASON_Step_not_Necessary", resourceCulture);
            }
        }
    }
}
